version: '3'
services:
  kpe:
    image: sdavidhdez/keyphrase-extraction:latest
    restart: always
    container_name: 'kpe'
    ports:
      - '8889:8888'
    volumes:
      - '.:/home/someuser/notebooks/keyphrase-extraction'
      - '/home/snov/nltk_data:/home/someuser/nltk_data'
      - './volumes/jupyter_notebook_config.py:/home/someuser/.jupyter/jupyter_notebook_config.py'
      - './volumes/.bashrc:/home/someuser/.bashrc'
      - './volumes/.bash_history:/home/someuser/.bash_history'
    # environment:
    #  - VIRTUAL_HOST=jlab.totum.one
    #  - VIRTUAL_PORT=8888
    #  - LETSENCRYPT_HOST= 'jlab.totum.one'

#networks:
#  default:
#    external:
#      name: webproxy
